use serde::{Deserialize, Serialize};
use strum_macros::EnumIter;

#[derive(Debug, Clone, Copy, EnumIter, Serialize, Deserialize)]
pub enum Scene {
    Ocean = 1,
    Romance,
    Sunset,
    Party,
    Fireplace,
    Cozy,
    Forest,
    PastelColors,
    Wakeup,
    Bedtime,
    WarmWhite,
    Daylight,
    Coolwhite,
    Nightlight,
    Focus,
    Relax,
    Truecolors,
    TVtime,
    Plantgrowth,
    Spring,
    Summer,
    Fall,
    Deepdive,
    Jungle,
    Mojito,
    Club,
    Christmas,
    Halloween,
    Candlelight,
    Goldenwhite,
    Pulse,
    Steampunk,
}

// to string
impl Scene {
    pub fn to_string(&self) -> String {
        match self {
            Scene::Ocean => String::from("Ocean"),
            Scene::Romance => String::from("Romance"),
            Scene::Sunset => String::from("Sunset"),
            Scene::Party => String::from("Party"),
            Scene::Fireplace => String::from("Fireplace"),
            Scene::Cozy => String::from("Cozy"),
            Scene::Forest => String::from("Forest"),
            Scene::PastelColors => String::from("Pastel Colors"),
            Scene::Wakeup => String::from("Wake Up"),
            Scene::Bedtime => String::from("Bedtime"),
            Scene::WarmWhite => String::from("Warm White"),
            Scene::Daylight => String::from("Daylight"),
            Scene::Coolwhite => String::from("Cool White"),
            Scene::Nightlight => String::from("Night Light"),
            Scene::Focus => String::from("Focus"),
            Scene::Relax => String::from("Relax"),
            Scene::Truecolors => String::from("True Colors"),
            Scene::TVtime => String::from("TV Time"),
            Scene::Plantgrowth => String::from("Plant Growth"),
            Scene::Spring => String::from("Spring"),
            Scene::Summer => String::from("Summer"),
            Scene::Fall => String::from("Fall"),
            Scene::Deepdive => String::from("Deep Dive"),
            Scene::Jungle => String::from("Jungle"),
            Scene::Mojito => String::from("Mojito"),
            Scene::Club => String::from("Club"),
            Scene::Christmas => String::from("Christmas"),
            Scene::Halloween => String::from("Halloween"),
            Scene::Candlelight => String::from("Candlelight"),
            Scene::Goldenwhite => String::from("Golden White"),
            Scene::Pulse => String::from("Pulse"),
            Scene::Steampunk => String::from("Steampunk"),
        }
    }
}
